# kind: Service
# apiVersion: v1
# metadata:
#   name: default-http-backend
# spec:
#   selector:
#     app: default-http-backend
#   ports:
#     - protocol: TCP
#       port: 8080
#       # targetPort: 8080
#   # type: NodePort