# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: swagger-ui
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: swagger-ui
#       role: master
#       tier: swagger
#   template:
#     metadata:
#       labels:
#         app: swagger-ui
#         role: master
#         tier: swagger
#     spec:
#       terminationGracePeriodSeconds: 60
#       containers:
#         - name: swagger-ui
#           image: swaggerapi/swagger-ui
#           env:
#             - name: API_URL
#               value: "http://127.0.0.1:8001/swaggerapi"
#           livenessProbe:
#             httpGet:
#               path: /healthz
#               port: 8080
#               scheme: HTTP
#             initialDelaySeconds: 30
#             timeoutSeconds: 5
#           ports:
#             - name: http
#               containerPort: 8080
#               protocol: TCP

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: swagger-ui
# spec:
#   selector:
#     app: swagger-ui
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8085
#   type: NodePort
